# ğŸ§© This file tells Flux how to build only the FRONTEND part.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml   # ğŸ§¼ Deploy React frontend
  - service.yaml      # ğŸŒ Expose frontend through a service
